%--------------------------------------------------------------------------
%
%   calculat the integrat function of the given polynomial in unit circle
%   input: x-polynomial variables; degree-polvnomial maximam degree
%   output: int_array-integral number of each monomial generated by x
%
%--------------------------------------------------------------------------

function array = Calculat_Obj(degree)

   syms x1 x2;
%     syms x1 x2 x3 x4;
    x=[x1,x2];
    X = monolist(x,degree);
    array=zeros(1,degree);
    for i = 1:length(X)
%        array(i)=double(int(int(X(i),x(2),-sqrt(1^2-x(1)^2),sqrt(1^2-x(1)^2)),x(1),-1,1));
%          array(i)=double(int(int(X(i),x(2),-sqrt(25-(x(1)-1.4)^2)-1.4,sqrt(25-(x(1)-1.4)^2)-1.4),x(1),-3.6,6.4)-int(int(X(i),x(2),-sqrt(0.25-(x(1)-1.4)^2)-1.4,sqrt(0.25-(x(1)-1.4)^2)-1.4),x(1),0.9,1.9));
%         array(i) = double(int(int(int(int(X(i),x4,-sqrt(1-(x1^2+x2^2+x3^2)),sqrt(1-(x1^2+x2^2+x3^2))),x3,-sqrt(1-(x1^2+x2^2)),sqrt(1-(x1^2+x2^2))),x2,-sqrt(1-x1^2),sqrt(1-x1^2)),x1,-1,1));
        
    end

    
